RenierM26/ha-ezviz

README.md

I append more precisions about the step adding the camera with the integration.

Add integration how to

---

README.md

I found little information after having issues to login using this integration. After some testing and researching I found an easy way to do it, and I think that having these instructions on the readme could help others like me.

Adds EZVIZ account setup instructions

---

custom_components/ezviz_cloud/config_flow.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/translations/en.json

Add MFA support to config_flow

---

custom_components/ezviz_cloud/config_flow.py

Fix reauth title error

---

custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/text.py

- BumpAPI to cleanup TextEntity.

BumpAPI and cleanup TextEntity

---

custom_components/ezviz_cloud/binary_sensor.py
custom_components/ezviz_cloud/button.py
custom_components/ezviz_cloud/camera.py
custom_components/ezviz_cloud/entity.py
custom_components/ezviz_cloud/image.py
custom_components/ezviz_cloud/light.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/number.py
custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/sensor.py
custom_components/ezviz_cloud/services.yaml
custom_components/ezviz_cloud/siren.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/switch.py
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/translations/en.json
custom_components/ezviz_cloud/update.py
hacs.json

- Follow translations order from latest hass pull requests. (Various pulls were merged in different order, just makes it easier)
- Add all the service name translations and older entity translations. (From hass code base)
- Cleanup siren with last pull changes.

Combine latest hass translation updates and cleanups.

---

custom_components/ezviz_cloud/entity.py
custom_components/ezviz_cloud/manifest.json

Fix base entity, DeviceInfo change not yet in latest release.

Fix base entity, DeviceInfo change not yet in latest release.

---

custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/siren.py

Update siren, reset scheduled off if triggered while on.

Update siren, reset scheduled off if triggered while on.

---

custom_components/ezviz_cloud/__init__.py
custom_components/ezviz_cloud/alarm_control_panel.py
custom_components/ezviz_cloud/button.py
custom_components/ezviz_cloud/camera.py
custom_components/ezviz_cloud/config_flow.py
custom_components/ezviz_cloud/coordinator.py
custom_components/ezviz_cloud/icons.json
custom_components/ezviz_cloud/image.py
custom_components/ezviz_cloud/light.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/number.py
custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/siren.py
custom_components/ezviz_cloud/switch.py
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/update.py

Update with new api name and official hass changes.

Update with new api name and official hass changes.

---

custom_components/ezviz_cloud/image.py

Fix password key error when ignored.

Fix password key error when ignored.

---

custom_components/ezviz_cloud/button.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/translations/en.json

Add Reboot button

---

custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/switch.py
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/translations/en.json

- Add enable/disable encryption switch entity.
- Fix text entity when changing encryption key.

Add enable/disable encryption switch entity.

---

custom_components/ezviz_cloud/entity.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/sensor.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/switch.py
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/translations/en.json

Add switches for:
- Offline notification
- Alarm push notification (in app and future mqtt)
- Call push notifications (in app and future mqtt)
- Device voice prompts.
Entity changes:
- Use camera online/offline status for switches. (will be unavailable if camera is disconnected)
Bump api version.

Add switches and bump api version

---

custom_components/ezviz_cloud/config_flow.py

- Re-use session for config flow instead of creating new one.
Improves config flow step reliability and speed.

Re-use ezviz_client when configuring new camera flow

---

custom_components/ezviz_cloud/entity.py

Add serial to device property, fix typing

Add serial to device property, fix typing

---

custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/translations/en.json

Add battery work mode to select entity.

Add battery work mode to select entity.

---

custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/translations/en.json

Add night vision mode select entity.

Add night vision mode select entity.

---

custom_components/ezviz_cloud/image.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/text.py

Get encryption password from text entity. Makes it much easier to enable image encryption if you have MFA enabled.

Image entity gets Encryption password from text entity.

---

custom_components/ezviz_cloud/__init__.py
custom_components/ezviz_cloud/config_flow.py

Fix config flow errors when ignored cameras config entries are present.

Fix config flow errors when ignored cameras are present.

---

custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/switch.py
custom_components/ezviz_cloud/translations/en.json

Add battery camera work mode for new AOV cameras.

Add battery camera work mode for new AOV cameras.

---

custom_components/ezviz_cloud/__init__.py
custom_components/ezviz_cloud/config_flow.py
custom_components/ezviz_cloud/const.py
custom_components/ezviz_cloud/image.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/translations/en.json

1) Updates authentication config_entry.
2) Registers MQTT client.
3) Fires events on ezviz_push_event
4) Updates image entity on mqtt notification.
5) Small fix to strings and en translation files. (That fixes the ugly looking text)

Initial support for mqtt image updates

---

README.md
custom_components/ezviz_cloud/__init__.py
custom_components/ezviz_cloud/camera.py
custom_components/ezviz_cloud/config_flow.py
custom_components/ezviz_cloud/const.py
custom_components/ezviz_cloud/image.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/translations/en.json

- More standards based.
- Would allow for multiple EZVIZ accounts.

Migrate fake camera config_entries to Ezviz cloud account options.

---

custom_components/ezviz_cloud/__init__.py
custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/media_source.py
custom_components/ezviz_cloud/strings.json
custom_components/ezviz_cloud/text.py
custom_components/ezviz_cloud/translations/en.json
custom_components/ezviz_cloud/views.py

Allows user to browse last alarm images in media browser

Initial media_source support for camera alarms

---

custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/select.py
custom_components/ezviz_cloud/text.py

- Improve select entity gating.
- Bump library (just linter fixes)
- linter fix on text.py

Improve select entity gating.

---

custom_components/ezviz_cloud/manifest.json
custom_components/ezviz_cloud/utility.py

Fix gating issue after utility refactor. (missing two select entities)

Fix gating in utility.py
